language: ruby
rvm:
  - jruby-1.7.6
  - jruby-head
jdk: openjdk7
services:
  - redis
  - rabbitmq
before_script:
  - psql -c "CREATE DATABASE travis_test;" -U postgres
  - cp config/travis.example.yml config/travis.yml
  - bundle exec rake db:setup
script: bundle exec rspec spec
matrix:
  allow_failures:
    - rvm: jruby-head
      jdk: openjdk7
